name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cms-api
        - uses: actions/checkout@v2
      - name: composer install
         run : |
           docker run --rm \
               -u "$(id -u):$(id -g)" \
               -v $(pwd):/var/www/html \
               -w /var/www/html \
               laravelsail/php80-composer:latest \
               composer install --ignore-platform-reqs
      - name: phpunit
        run: |
          docker-compose up -d
          composer install
          docker-compose exec bash -c "php artisan migrate:fresh; ./vendor/bin/phpunit "
